backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Focus Keyword", name: "yoast_keyword", widget: "string"}
      - {label: "Meta Description", name: "yoast_description", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "One Column"
                name: "one-column"
                widget: object
                fields:
                  - label: "Background"
                    name: "background"
                    widget: "list"
                    types:
                      - label: "Color"
                        name: "bg_color"
                        widget: object
                        field: {label: "Color", name: "bg_color_color", widget: "color"}
                      - label: "Image"
                        name: "bg_image"
                        widget: object
                        field: {label: "Image", name: "bg_image_image", widget: "image"}
                      - label: "Gradient"
                        name: "bg_gradient"
                        widget: object
                        fields:
                          - {label: "Left", name: "bg_gradient_l", widget: "color"}
                          - {label: "Right", name: "bg_gradient_r", widget: "color"}
                  - {label: "Header", name: "header", widget: "markdown"}
                  - {label: "Column 1", name: "column_1", widget: "markdown"}
                  - {label: "Footer", name: "footer", widget: "markdown"}
              - label: "Two Column"
                name: "two-column"
                widget: object
                fields:
                  - label: "Background"
                    name: "background"
                    widget: "list"
                    types:
                      - label: "Color"
                        name: "bg_color"
                        widget: object
                        field: {label: "Color", name: "bg_color_color", widget: "color"}
                      - label: "Image"
                        name: "bg_image"
                        widget: object
                        field: {label: "Image", name: "bg_image_image", widget: "image"}
                      - label: "Gradient"
                        name: "bg_gradient"
                        widget: object
                        fields:
                          - {label: "Left", name: "bg_gradient_l", widget: "color"}
                          - {label: "Right", name: "bg_gradient_r", widget: "color"}
                  - {label: "Header", name: "header", widget: "markdown"}
                  - {label: "Column 1", name: "column_1", widget: "markdown"}
                  - {label: "Column 2", name: "column_2", widget: "markdown"}
                  - {label: "Footer", name: "footer", widget: "markdown"}
  - name: "pages2" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages2" # Used in the UI, ie.: "New Post"
    folder: "site/content/pages2" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: Image, name: image, widget: image}
      - {label: "Focus Keyword", name: "yoast_keyword", widget: "string"}
      - {label: "Meta Description", name: "yoast_description", widget: "string"}
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "One Column"
            name: "one-column"
            widget: object
            fields:
              - label: "Background"
                name: "background"
                widget: "list"
                types:
                  - label: "Color"
                    name: "bg_color"
                    widget: object
                    field: {label: "Color", name: "bg_color_color", widget: "color"}
                  - label: "Image"
                    name: "bg_image"
                    widget: object
                    field: {label: "Image", name: "bg_image_image", widget: "image"}
                  - label: "Gradient"
                    name: "bg_gradient"
                    widget: object
                    fields:
                      - {label: "Left", name: "bg_gradient_l", widget: "color"}
                      - {label: "Right", name: "bg_gradient_r", widget: "color"}
              - {label: "Header", name: "header", widget: "markdown"}
              - {label: "Column 1", name: "column_1", widget: "markdown"}
              - {label: "Footer", name: "footer", widget: "markdown"}
          - label: "Two Column"
            name: "two-column"
            widget: object
            fields:
              - {label: "Header", name: "header", widget: "markdown"}
              - {label: "Column 1", name: "column_1", widget: "markdown"}
              - {label: "Column 2", name: "column_2", widget: "markdown"}
              - {label: "Footer", name: "footer", widget: "markdown"}
